"""empty message

Revision ID: 82902ffc468a
Revises: 73da07cbd495
Create Date: 2019-02-26 13:39:43.567867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82902ffc468a'
down_revision = '73da07cbd495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('category', sa.String(), server_default='misc', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'category')
    # ### end Alembic commands ###
