"""empty message

Revision ID: 9b7ac7a8d6d4
Revises: ffc5fd26716b
Create Date: 2019-02-27 17:38:28.085692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b7ac7a8d6d4'
down_revision = 'ffc5fd26716b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tweets_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'ban')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ban', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'tweets_count')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
