"""empty message

Revision ID: c76ed65c899c
Revises: 82902ffc468a
Create Date: 2019-02-27 14:57:20.169614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76ed65c899c'
down_revision = '82902ffc468a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.Column('ban', sa.Boolean(), nullable=True),
    sa.Column('profile_image_url_https', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'tweets', 'users', ['user_id'], ['id'])
    op.drop_column('tweets', 'profile_image_url_https')
    op.drop_column('tweets', 'urls')
    op.drop_column('tweets', 'screen_name')
    op.drop_column('tweets', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tweets', sa.Column('screen_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tweets', sa.Column('urls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tweets', sa.Column('profile_image_url_https', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
