"""empty message

Revision ID: d903410f54e0
Revises: 9b7ac7a8d6d4
Create Date: 2019-02-27 22:03:26.380635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd903410f54e0'
down_revision = '9b7ac7a8d6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('user_description', sa.String(), nullable=True))
    op.add_column('tweets', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('tweets', sa.Column('user_profile_image_url_https', sa.String(), nullable=True))
    op.add_column('tweets', sa.Column('user_screen_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'user_screen_name')
    op.drop_column('tweets', 'user_profile_image_url_https')
    op.drop_column('tweets', 'user_name')
    op.drop_column('tweets', 'user_description')
    # ### end Alembic commands ###
